name: 01-Workflow Events

on:
# push :
 workflow_dispatch:

jobs:
    echo:
      runs-on: ubuntu-latest
      steps:
        - name: Show the Trigger
          run: echo "I am on master branch! and have been triggered by a ${{github.event_name}} event"
