name: 06-Contexts
#run-name: 06 - Contexts | Debug - ${{ inputs.debug }}
run-name: 06 - Contexts | Debug - ${{ github.event_name == 'workflow_dispatch' && inputs.debug || 'N/A' }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:                 # <- job id (required)
    name: echo-data          # <- job name (optional, for display)
    runs-on: ubuntu-latest
    env: 
        MY_JOB_VAR: 'job'
        MY_OVERWRITTEN_VAR: 'job'

    steps:
      - name: Display Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Job: ${{ github.job }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Run Number: ${{ github.run_number }}"

      - name: Retrieve variable
        run: |
            echo "Variable value =  ${{ vars.MY_VAR }} ".

      - name: Display Environment Variables
        env:
            MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow ENV Variable: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten ENV Variable: ${{ env.MY_OVERWRITTEN_VAR }}"

      - name: Display Job  Variables
        run: |
          echo "Workflow ENV Variable: ${{ env.MY_WORKFLOW_VAR }}"
          echo "Overwritten ENV Variable: ${{ env.MY_OVERWRITTEN_VAR }}"

  ech-data2:
    name: echo-data-2
    runs-on: ubuntu-latest

    steps:
      - name: Display Information
        run: |
          echo "Workflow ENV Variable: $MY_WORKFLOW_VAR"
          echo "Overwritten ENV Variable: $MY_OVERWRITTEN_VAR"            