name: 07 - Expressions
run-name: 07 - using Expressions | Debug - ${{ (github.event_name == 'workflow_dispatch' && inputs.debug) && 'ON' || 'OFF' }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: true

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] print start-up data"
        if: github.event_name == 'workflow_dispatch' && inputs.debug
        run: |
          echo "Triggered by: ${{ github.event_name }} event"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"

      - name: "[debug] print when triggered from main"
        if: github.event_name == 'workflow_dispatch' && inputs.debug && github.ref == 'refs/heads/main'
        run: |
          echo "I was triggered from the main branch."

      - name: Print Greeting
        run: |
          echo "Hello, World !!!"