name: 08 - Using variables
on: 
  push:
  workflow_dispatch:
env:
  WORKFLOW_VAR: "I am a workflow env variable"
  OVERWRITTEN: "I will be overwritten"
  UNDEFINED_VAR_WITH_DEFAULT: ${{ vars.UNDEFINED_VAR || 'default VALUE' }}
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: "I am a job env variable"
      OVERWRITTEN: "I am overwritten at job level"
    steps:
      - name: Print env variables
        env:
          STEP_VAR: "I am a step env variable"
          step_var2: "I am another step env variable"
        run: |
          echo "Step env var: $STEP_VAR"
          echo "Step env var1: ${{ env.STEP_VAR }}"
          echo "Step env var2: $step_var2"
          echo "Job env var: $JOB_VAR"
          echo "Workflow env var: $WORKFLOW_VAR"
          echo "Overwritten var: $OVERWRITTEN"

      - name: Overwrite job variable at step level
        env:
          OVERWRITTEN: "I am overwritten at step level"
        run: |
          echo "Overwritten var at step level: $OVERWRITTEN"

  echo2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variables
        run: |
            echo "Org Var: ${{ vars.ORG_VAR }}"
            echo "Org overwritten Var: ${{ vars.OVERWRITTEN_VAR }}"
            echo "Repo Var: ${{ vars.REPOSITORY_VAR }}"
  echo-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Print Variables
        run: |
            echo "Org Var: ${{ vars.ORG_VAR }}"
            echo "Org overwritten Var: ${{ vars.OVERWRITTEN_VAR }}"
            echo "Repo Var: ${{ vars.REPOSITORY_VAR }}"
            echo "Environment Var: ${{ vars.TARGET_VAR }}"

  echo-undefined:
    runs-on: ubuntu-latest
    steps:
      - name: Print Undefined  Variables
        run: |
            echo "Org Var: ${{ vars.UNDEFINED_VAR || 'default VALUE' }}"
            echo "Org overwritten Var: ${{ vars.OVERWRITTEN_VAR }}"
            echo "Repo Var: ${{ vars.REPOSITORY_VAR }}"