name: 09 - functions
on:
  pull_request:
  workflow_dispatch:
jobs:
    echo1:
      runs-on: ubuntu-latest
      steps:
        - name: Sleep for 20 seconds
          run: sleep 20    
        - name: Failing Step
          run: |
            echo "This step will fail to demonstrate the use of functions."
            exit 1
        - name: I will be skipped
          if: ${{ success() }}
          run : echo "I will print if previous steps succeed"
        - name: Test endsWith function
          if: ${{ failure() }}
          run: echo "I will print if previous steps fail
        - name: I will execute always
          if: ${{ !cancelled() }}
          run:  echo "I will always print except when the workflow is cancelled"
        - name: I will execute when cancelled
          if: ${{ cancelled() }}
          run:  echo "I will always print except when the workflow is cancelled"