name: 11 - Working with Inputs
on:
  workflow_dispatch:
    inputs:
        dry-run:
          description: 'Skip deployment and only print build output'
          # type can be string, boolean, choice, or environment
          type: boolean
          required: false
          default: true

        target:
          description: 'Which env the workflow will target'
          required: true
#          default: 'staging'
          type: environment
        #   options:
        #      - staging
        #      - production

        tag:
          description: 'Release from which to build and deploy'
          required: false
          type: choice
          default: v3
          options:
            - v1
            - v2
            - v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Building the project from tag: ${{ inputs.tag }}"

  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target}}
    needs: build
    steps:
      - name: Deploy
        if: ${{ success() }}
        run: |
          echo "Deploying to ${{ inputs.target }} from tag: ${{ inputs.tag }}"