name: 14 - working with artifacts

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache step
        type: boolean
        default: true
      node-version:
        description: Node version
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x

jobs:
  test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 14-artifacts/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 14-artifacts/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Unit tests
        run: npm run test
      - name: Build Code
        run: npm run build
      - name: Upload Build Files
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: 14-artifacts/react-app/build
  deploy:
    runs-on: ubuntu-latest
    needs: test-build
    steps:
      - name: Download Build Files
        uses: actions/download-artifact@v4
        with:
          name: app
          path: 14-artifacts/react-app/build
      - name: Show folder structure
        run: |
          ls -R