name: 18.1-Reusable Workflows
on:
    workflow_call:
        inputs:
            target-directory:
                description: The directory to deploy the build artifacts to
                type: string
                required: true
        outputs:
            build-status:
                description: The status of the build
                value: ${{ jobs.deploy.outputs.build-status }}
            url:
                description: The URL of the deployed build artifacts
                value: ${{ jobs.deploy.outputs.url }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{ steps.build.outputs.build-status }}
            url: ${{ steps.deploy.outputs.url }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build
              id: build
              run: 
                echo "Building the project...${{ inputs.target-directory }}"
                echo "build-status=success" >> $GITHUB_OUTPUT
            - name: Deploy
              id: deploy
              run:
                echo "Deploying build artifacts.."
                echo "url=https://www.google.com" >> "$GITHUB_OUTPUT"
