name: 18.2 - Reusable Workflow Caller
on: 
    workflow_dispatch:

jobs:
    deploy:
        uses: ./.github/workflows/18-1-ResuableWorkflows.yaml
        with:
            target-directory: dummy-dir
    outputs:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Print Outputs
              run: |
                echo "Build status: ${{ needs.deploy.outputs.build-status }}"
                echo "URL: ${{ needs.deploy.outputs.url }}"